# -*- coding: utf-8 -*-
"""co2_soil_monitoring_script.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jp_QdURDdEwMeDSVzTZpuFsEtN_OrXDd
"""

#!/usr/bin/env python3
import pandas as pd
from datetime import datetime, timedelta
from pytz import timezone
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import re

# =========================
# CONFIG
# =========================
CHICAGO_TZ = timezone("America/Chicago")

# Update these to match your exact file names!
REG_CSV_FILE = "FILE NAME HERE"
CONTROL_CSV_FILE = "FILE NAME HERE"
OUTPUT_FILE = "output_comparison.png"

plot_title = "Experiment vs Control Sensor Data (RNA Group)"

# Light schedule (hour, minute)
LIGHT_ON = (10, 0)   # 10:00 AM
LIGHT_OFF = (22, 0)  # 10:00 PM

# =========================
# Parse CSV files
# =========================
def load_sensor_data(csv_file, pattern):
    """Loads CSV and extracts values using a specific Regex pattern."""
    df = pd.read_csv(csv_file, encoding='utf-8', encoding_errors='ignore')

    # Extract data using the regex pattern
    extracted = df['Raw'].str.extract(pattern)
    df = pd.concat([df, extracted], axis=1)

    # Convert Timestamp to datetime
    df['Timestamp'] = pd.to_datetime(df['Timestamp'], errors='coerce')

    # Convert extracted columns to numeric
    for col in ['CO2', 'SCD_T', 'SCD_H']:
        df[col] = pd.to_numeric(df[col], errors='coerce')

    # Drop rows with missing data (this filters out [WARN] and headers)
    df = df.dropna(subset=['CO2', 'SCD_T', 'SCD_H', 'Timestamp'])

    # Localize the timezone
    df["Timestamp"] = df["Timestamp"].dt.tz_localize(CHICAGO_TZ, ambiguous='NaT', nonexistent='shift_forward')

    return df.sort_values("Timestamp").reset_index(drop=True)

# =========================
# Create plot
# =========================
def make_figure(df_reg, df_control):
    fig, (ax1, ax2, ax3) = plt.subplots(3, 1, figsize=(16, 9), sharex=True)

    # Get combined data range to ensure shading covers everything
    min_time = min(df_reg["Timestamp"].min(), df_control["Timestamp"].min())
    max_time = max(df_reg["Timestamp"].max(), df_control["Timestamp"].max())
    start_date = min_time.date()
    end_date = max_time.date()

    # Add day/night shading for each day
    current = start_date
    while current <= end_date:
        day_start = CHICAGO_TZ.localize(datetime.combine(current, datetime.min.time()))
        light_on = day_start + timedelta(hours=LIGHT_ON[0], minutes=LIGHT_ON[1])
        light_off = day_start + timedelta(hours=LIGHT_OFF[0], minutes=LIGHT_OFF[1])
        day_end = day_start + timedelta(days=1)

        # Night: midnight to light-on (dark grey)
        for ax in [ax1, ax2, ax3]:
            ax.axvspan(day_start, light_on, alpha=0.3, color='darkgrey', zorder=0)
            # Night: light-off to midnight (dark grey)
            ax.axvspan(light_off, day_end, alpha=0.3, color='darkgrey', zorder=0)

        current += timedelta(days=1)

    # Plot CO2
    ax1.plot(df_reg["Timestamp"], df_reg["CO2"], 'o', markersize=2, color='green', label="Experiment")
    ax1.plot(df_control["Timestamp"], df_control["CO2"], 'o', markersize=2, color='purple', alpha=0.6, label="Control")
    ax1.set_ylabel("CO₂ (ppm)", fontsize=12)
    ax1.set_title("CO₂", fontsize=14, fontweight='bold')
    ax1.grid(True, alpha=0.3)
    ax1.legend(loc="upper left")

    # Plot Humidity
    ax2.plot(df_reg["Timestamp"], df_reg["SCD_H"], 'o', markersize=2, color='blue', label="Experiment")
    ax2.plot(df_control["Timestamp"], df_control["SCD_H"], 'o', markersize=2, color='orange', alpha=0.6, label="Control")
    ax2.set_ylabel("Humidity (%)", fontsize=12)
    ax2.set_title("Humidity", fontsize=14, fontweight='bold')
    ax2.grid(True, alpha=0.3)
    ax2.legend(loc="upper left")

    # Plot Temperature
    ax3.plot(df_reg["Timestamp"], df_reg["SCD_T"], 'o', markersize=2, color='red', label="Experiment")
    ax3.plot(df_control["Timestamp"], df_control["SCD_T"], 'o', markersize=2, color='black', alpha=0.6, label="Control")
    ax3.set_ylabel("Temperature (°C)", fontsize=12)
    ax3.set_title("Temperature", fontsize=14, fontweight='bold')
    ax3.grid(True, alpha=0.3)
    ax3.legend(loc="upper left")

    # Format x-axis: show 10 AM and 10 PM for each day
    ticks = []
    current = start_date
    while current <= end_date:
        day = CHICAGO_TZ.localize(datetime.combine(current, datetime.min.time()))
        ticks.append(day + timedelta(hours=10))  # 10 AM
        ticks.append(day + timedelta(hours=22))  # 10 PM
        current += timedelta(days=1)

    ax3.set_xticks(ticks)
    ax3.xaxis.set_major_formatter(mdates.DateFormatter('%B %d, %I %p', tz=CHICAGO_TZ))
    plt.setp(ax3.xaxis.get_majorticklabels(), rotation=-30, ha='left')

    # Set x-axis limits to data range (no extra padding)
    ax3.set_xlim(min_time, max_time)

    fig.suptitle(plot_title, fontsize=16, fontweight='bold')
    ax3.set_ylim(15, 35) # Fixed range: 15°C to 35°C
    plt.tight_layout()

    return fig

# =========================
# Main
# =========================
if __name__ == "__main__":
    # Define the specific text patterns for each file
    reg_pattern = r"CO2 concentration \[ppm\]: (?P<CO2>\d+), Temperature \[°C\]: (?P<SCD_T>[\d.]+), Relative Humidity \[RH\]: (?P<SCD_H>[\d.]+)"
    control_pattern = r"co2=(?P<CO2>\d+) ppm, scd_t=(?P<SCD_T>[\d.]+) C, scd_h=(?P<SCD_H>[\d.]+) %"

    print(f"Loading {REG_CSV_FILE}...")
    df_reg = load_sensor_data(REG_CSV_FILE, reg_pattern)
    print(f"Loaded {len(df_reg)} experiment data points")

    print(f"Loading {CONTROL_CSV_FILE}...")
    df_control = load_sensor_data(CONTROL_CSV_FILE, control_pattern)
    print(f"Loaded {len(df_control)} control data points")

    print("Creating plot...")
    fig = make_figure(df_reg, df_control)

    print(f"Saving {OUTPUT_FILE}...")
    fig.savefig(OUTPUT_FILE, dpi=300, bbox_inches='tight')

    plt.show()
    print("Done!")

"""Soil Sensor Data Plot"""

##!/usr/bin/env python3

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from datetime import datetime, timedelta
from pytz import timezone

# =========================
# CONFIG
# =========================
CHICAGO_TZ = timezone("America/Chicago")

# Update these to match your exact file names
CSV_FILE = "/content/D112_ttyACM1_CAmb_Elena_Moisture_Feb24.csv"
OUTPUT_FILE = "soil_output.png"

plot_title = "TEROS-12 Soil Sensor Data"

# Day/Night shading schedule
LIGHT_ON = (10, 0)
LIGHT_OFF = (22, 0)

# =========================
# Parse Data
# =========================
def load_soil_data(csv_file):
    df = pd.read_csv(csv_file, encoding='utf-8', encoding_errors='ignore')

    # Corrected Regex:
    # Skips the first 5 metadata values, then captures Measurement 1 (Raw VWC), Measurement 2 (Temp), and Measurement 3 (EC)
    pattern = r"^\d+,\s*\d+,\s*\d+,\s*\d+,\s*\d+,\s*(?P<VWC_RAW>[\d.]+),\s*(?P<TEMP>[\d.]+),\s*(?P<EC>[\d.]+),"

    extracted = df['Raw'].str.extract(pattern)
    df = pd.concat([df, extracted], axis=1)

    df['Timestamp'] = pd.to_datetime(df['Timestamp'], errors='coerce')
    df['VWC_RAW'] = pd.to_numeric(df['VWC_RAW'], errors='coerce')
    df['TEMP'] = pd.to_numeric(df['TEMP'], errors='coerce')
    df['EC'] = pd.to_numeric(df['EC'], errors='coerce')

    # Apply the generic mineral soil calibration equation from the TEROS 12 manual
    df['VWC'] = (3.879e-4 * df['VWC_RAW']) - 0.6956

    # Drop non-data rows
    df = df.dropna(subset=['Timestamp', 'VWC'])

    df["Timestamp"] = df["Timestamp"].dt.tz_localize(CHICAGO_TZ, ambiguous='NaT', nonexistent='shift_forward')
    return df.sort_values("Timestamp")

# =========================
# Plotting
# =========================
def plot_soil(df):
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(15, 10), sharex=True)

    # Shading logic
    start_date = df["Timestamp"].min().date()
    end_date = df["Timestamp"].max().date()
    current = start_date
    while current <= end_date:
        day_start = CHICAGO_TZ.localize(datetime.combine(current, datetime.min.time()))
        light_on = day_start + timedelta(hours=LIGHT_ON[0])
        light_off = day_start + timedelta(hours=LIGHT_OFF[0])
        day_end = day_start + timedelta(days=1)
        for ax in [ax1, ax2]:
            ax.axvspan(day_start, light_on, color='lightgrey', alpha=0.3)
            ax.axvspan(light_off, day_end, color='lightgrey', alpha=0.3)
        current += timedelta(days=1)

    # Subplot 1: Volumetric Water Content
    ax1.plot(df["Timestamp"], df["VWC"], color='blue', linewidth=1.5, label="Soil Moisture")
    ax1.set_ylabel("Volumetric Water Content ($m^3/m^3$)", fontsize=12)
    ax1.set_title("Soil Moisture", fontweight='bold')
    ax1.grid(True, alpha=0.3)

    # Subplot 2: Soil Temperature
    ax2.plot(df["Timestamp"], df["TEMP"], color='red', linewidth=1.5, label="Soil Temp")
    ax2.set_ylabel("Temperature (°C)", fontsize=12)
    ax2.set_title("Soil Temperature", fontweight='bold')
    ax2.grid(True, alpha=0.3)

    # X-Axis Formatting
    ax2.xaxis.set_major_formatter(mdates.DateFormatter('%b %d\n%I %p', tz=CHICAGO_TZ))
    ax2.set_xlim(df["Timestamp"].min(), df["Timestamp"].max())

    fig.suptitle(plot_title, fontsize=16, fontweight='bold')
    plt.tight_layout(rect=[0, 0.03, 1, 0.95])
    return fig

# =========================
# Main
# =========================
if __name__ == "__main__":
    print(f"Parsing {CSV_FILE}...")
    soil_df = load_soil_data(CSV_FILE)

    if not soil_df.empty:
        print(f"Plotting {len(soil_df)} data points...")
        fig = plot_soil(soil_df)
        fig.savefig(OUTPUT_FILE, dpi=300)
        plt.show()
    else:
        print("No valid data found.")