# -*- coding: utf-8 -*-
"""transcript_categorization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zs3ff13WaB9jLlw2S097MbR6BsnOiuuN
"""

# ── Install dependencies (run this cell first in Colab) ──────────────────────
# !pip install openpyxl matplotlib

import openpyxl
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np
from collections import Counter
from google.colab import files

# ── 1. Load the xlsx ──────────────────────────────────────────────────────────
# Upload your file when prompted
uploaded = files.upload()
filename = list(uploaded.keys())[0]

wb = openpyxl.load_workbook(filename)
ws = wb.active

rows = []
for row in ws.iter_rows(values_only=True):
    if row[0] and row[0] != "transcriptome_vs_arabidopsis" and row[10] is not None:
        rows.append({
            "query":    row[0],
            "evalue":   float(row[10]),
            "bitscore": float(row[11]),
            "desc":     row[12],
        })

print(f"Loaded {len(rows)} hits")

# ── 2. Categorize each hit ────────────────────────────────────────────────────
def categorize(desc):
    d = desc.lower()
    if any(x in d for x in ["photosystem", "photosynthetic", "light-harvesting", "ohp1",
                              "proton gradient", "pgr5", "ycf54", "ferredoxin", "psbp", "psbo",
                              "slow green", "lir1", "light-regulated"]):
        return "Photosynthesis"
    if any(x in d for x in ["glycine dehydrogenase", "glycine cleavage", "enolase",
                              "pyruvate dehydrogenase", "glyceraldehyde", "gapb",
                              "trehalose", "galactinol", "galactosyltransferase",
                              "pyrophosphatase", "amidophosphoribosyl", "sarcosine oxidase",
                              "3-hydroxyisobutyrate", "fatty acid", "ketoacyl"]):
        return "Metabolism"
    if any(x in d for x in ["ribosomal", "ribosome", "ubiquitin-ribosomal", "elongation factor"]):
        return "Ribosomal / Translation"
    if any(x in d for x in ["superoxide dismutase", "thioredoxin", "iron-sulfur",
                              "stress-associated", "chaperone", "dnaj", "abc transporter"]):
        return "Stress / Redox"
    if any(x in d for x in ["lipid-transfer", "ltp", "ketoacyl-coa synthase"]):
        return "Lipid / Wax"
    if any(x in d for x in ["udp-glycosyltransferase", "cytochrome p450", "s-adenosylmethionine",
                              "ammonium transporter", "translocase", "signal peptidase",
                              "membrane steroid", "tim22", "nadh dehydrogenase",
                              "callose synthase", "calcium-binding", "feronia",
                              "ubiquitin-protein ligase", "f-box", "pentatricopeptide",
                              "molybdopterin", "zinc finger", "oberon", "alfin",
                              "mizu", "mctp", "pp2ab", "caf1", "nrt1"]):
        return "Signaling / Regulation"
    return "Other"

for r in rows:
    r["category"] = categorize(r["desc"])

# ── 3. Color palette (Northwestern purple tones) ─────────────────────────────
palette = {
    "Photosynthesis":          "#7628c5",
    "Metabolism":              "#7628c5",
    "Stress / Redox":          "#7628c5",
    "Ribosomal / Translation": "#7628c5",
    "Lipid / Wax":             "#7628c5",
    "Signaling / Regulation":  "#7628c5",
    "Other":                   "#7628c5",
}

category_order = list(palette.keys())

# ── CHART 1: Bar chart of functional categories ───────────────────────────────
cat_counts = Counter(r["category"] for r in rows)
cats  = [c for c in category_order if c in cat_counts]
counts = [cat_counts[c] for c in cats]
bar_colors = [palette[c] for c in cats]

fig1, ax1 = plt.subplots(figsize=(9, 5))
fig1.patch.set_facecolor("white")
ax1.set_facecolor("white")

bars = ax1.bar(cats, counts, color=bar_colors, edgecolor="none", width=0.6)
for bar, val in zip(bars, counts):
    ax1.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.3,
             str(val), ha="center", va="bottom", color="#000000", fontsize=10, fontweight="bold")

ax1.set_ylabel("Number of Transcripts", color="#000000", fontsize=11)
ax1.set_title("Functional Categories of Identified Transcripts\nColeus amboinicus",
              color="#000000", fontsize=13, fontweight="bold", pad=12)
ax1.tick_params(axis="x", colors="#000000", labelsize=9, rotation=20)
ax1.tick_params(axis="y", colors="#000000")
for spine in ax1.spines.values():
    spine.set_edgecolor("#ffffff")
ax1.yaxis.grid(True, color="#2d1050", linestyle="--", linewidth=0.8)
ax1.set_axisbelow(True)

plt.tight_layout()
#plt.savefig("chart1_categories.png", dpi=300, bbox_inches="tight", facecolor=fig1.get_facecolor())
plt.show()
print("Saved: chart1_categories.png")